# for testing my compiles
project: Project1.c BurnUtility.c Scheduler.c
	gcc -D ALYSSA_TESTING -o test Project1.c BurnUtility.c Scheduler.c
test2: Project1.c BurnUtility.c Scheduler.c
	gcc -D TEST2 -D ALYSSA_TESTING -o test2 Project1.c BurnUtility.c Scheduler.c
test3: Project1.c BurnUtility.c Scheduler.c
	gcc -D TEST3 -D ALYSSA_TESTING -o test3 Project1.c BurnUtility.c Scheduler.c
